"""
monitoring.py — Prediction Logging for Drift Detection
======================================================
Logs every prediction generated by the Signal Engine.
Useful for checking signal distribution over time during paper/live trading.
"""

import os
import pandas as pd
import logging
from datetime import datetime

import config

logger = logging.getLogger(__name__)


def log_prediction(signal_data: dict, filepath: str = None):
    """
    Append a prediction to the monitoring log.
    
    Parameters
    ----------
    signal_data : dict
        Output from signal_engine.generate_signal().
    filepath : str
        Path to CSV log file.
    """
    filepath = filepath or config.PREDICTION_LOG_FILE
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    
    # Flatten/format data
    log_entry = {
        "log_time": datetime.now().isoformat(),
        "candle_time": signal_data.get("timestamp"),
        "model_version": signal_data.get("model_version", "N/A"),
        "signal": signal_data.get("signal"),
        "confidence": signal_data.get("confidence", 0.0),
        "entry_price": signal_data.get("entry_price", 0.0),
        "reason": signal_data.get("reason", "")
    }
    
    df = pd.DataFrame([log_entry])
    
    # Append to CSV
    if not os.path.exists(filepath):
        df.to_csv(filepath, index=False)
    else:
        df.to_csv(filepath, mode="a", header=False, index=False)
        
        
def get_prediction_stats(filepath: str = None) -> dict:
    """
    Read the prediction log and compute distribution stats.
    Useful for detecting model drift (e.g., if it suddenly only predicts HOLD).
    """
    filepath = filepath or config.PREDICTION_LOG_FILE
    
    if not os.path.exists(filepath):
        logger.warning(f"Prediction log not found: {filepath}")
        return {}
        
    df = pd.read_csv(filepath)
    
    if df.empty:
        return {}
        
    total = len(df)
    counts = df["signal"].value_counts()
    
    stats = {
        "total_predictions": total,
        "distribution": {
            sig: {"count": int(count), "pct": float(count/total*100)} 
            for sig, count in counts.items()
        },
        "avg_confidence": {
            sig: float(df[df["signal"] == sig]["confidence"].mean())
            for sig in counts.index if sig in ["BUY", "SELL"]
        }
    }
    
    return stats
